### ISSUE TITLE
Underlying assumptions for ANCOM 2.1

### ISSUE THREAD

**Issue by skoepper** [FrederickHuangLin/Microbiome-Analyses-Review#3]
Hello, 

I am using ancom 2.1 for the differential abundance analysis of my microbiome data. To understand how the method work, I read the supplementary material of Mandal et al. (2015), and it states that there are three assumptions for ancom: 
1. Flexible. If distributional assumptions needed for standard ANOVA are not satised then non- parametric methods including resampling procedures can be used.
2. Either (a) The mean abundance of at most p-2 taxa are different between two populations, or (b) If all p taxa are differentially abundant then the mean abundance of all p taxa do not differ by the same amount between two populations. But if they do, then the difference is zero.

Based on the code I believe assumption 2b is used, but I would be happy for a clarification on this. 

Thanks, 
Svenja

**Comment by FrederickHuangLin** [comment]
I believe this question has been addressed by email. For other readers who have a similar question, I copied my reply in below:

> To address your specific questions:

> 1. The first point seems to pertain more to the capabilities of ANCOM rather than its underlying assumptions. If my recollection serves me correctly, ANCOM 2.1 does indeed support nonparametric tests.

> 2. The ANCOM model relies on two fundamental assumptions you found to ensure the validity of statistical inferences. These assumptions are integral to the inherent formula of ANCOM. When discussing assumptions, it's crucial to connect them with the methodology rather than the code implementation. The code itself serves as a means of executing the methodology and thus must adhere to the underlying assumptions of ANCOM for making conclusions.

Best regards,
Huang
